### PR TITLE
Set an environment variable per subprocess

### PR DESCRIPTION
**Pull request by boxed**
This makes it easy to create external resources based on worker ID, e.g. databases.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
I'm reluctant to introduce a blob that way giving the information is available via the configuration already

**Comment by boxed** [comment]
So how would I get to that configuration data?

**Comment by RonnyPfannschmidt** [comment]
`request.config.slaveinput` on any fixture setup

**Comment by boxed** [comment]
What is "request"? 

The use case I have is for selecting DB name in the settings of a django app. Then I'd need some try import except importererror thing too?

**Comment by RonnyPfannschmidt** [comment]
request is a fixture made by pytest that can be used for setup, it exposes the config object

**Comment by boxed** [comment]
Hmm.. Can I programmatically get access to pytest fixtures that early do you think?

**Comment by RonnyPfannschmidt** [comment]
define early, how do you create databases? database creation should be a session scoped fixture

**Comment by boxed** [comment]
Earlier than pytest-django starts reading settings and creating databases :P

**Comment by RonnyPfannschmidt** [comment]
sounds like pytest-django needs proper xdist support

**Comment by boxed** [comment]
Or vice versa.

**Comment by RonnyPfannschmidt** [comment]
xdist already provides the information, pytest-django just does not use them yet

**Comment by RonnyPfannschmidt** [comment]
according to @pelme pytest-django already sets up test databases according to xdist gateway names

**Comment by pelme** [comment]
@boxed Yes, xdist should be supported directly by pytest-django:

There is a note in the FAQ on xdist support.
https://pytest-django.readthedocs.org/en/latest/faq.html#does-pytest-django-work-with-the-pytest-xdist-plugin 

pytest-django uses `request.slaveinput` as described by ronny:
https://github.com/pytest-dev/pytest-django/blob/7afcca4059dbd0939de72ce27d22316ffb368413/pytest_django/fixtures.py#L33-L39

Here are tests:
https://github.com/pytest-dev/pytest-django/blob/7afcca4059dbd0939de72ce27d22316ffb368413/tests/test_db_setup.py#L127-L219

Please open a pytest-django issue if you find any problems with the xdist support! :)

**Comment by boxed** [comment]
Huh. I guess we're on an old version or have otherwise screwed this up at work! Thank you very much for doing this research.

**Pull request closed without merging**
