### PR TITLE
Typo fixes to docstrings

### PR DESCRIPTION
**Pull request by nchammas**
Apologies if I've misunderstood the original intention behind any of the original text and made an inappropriate change. Let me know and I'd be happy to make the appropriate adjustments.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
it looks good at first glance, but i myself cant take a propper look at it until the weekend

**Comment by nchammas** [comment]
No worries. Take your time.

**Comment by nicoddemus** [comment]
Thanks a lot @nchammas! :smile:

@RonnyPfannschmidt took the liberty to merge it, all pertinent typos. :smile:

**Comment by nchammas** [comment]
:+1:

**Comment by RonnyPfannschmidt** [comment]
:+1:

**Pull request merged**
