### PR TITLE
Remove deprecated "slave" aliases

### PR DESCRIPTION
**Pull request by Zac-HD**
We started this process in 2017 with #234, and it's time to complete it.  Xref https://github.com/pytest-dev/pytest/issues/7344

Implementation note: after  is in a released version of pytest, I'll bump the `pytest` required version for `pytest-xdist` and then merge this :slightly_smiling_face: 

- [x] Merge https://github.com/pytest-dev/pytest/pull/7356 for upstream `pytest` support
- [x] Bump minimum dependency version to `pytest >= 6.0.0` (after that release)
- [x] Fix other plugin compatibility issues linked below
  - [x] PRs opened for all plugins
  - [x] PRs merged for all plugins
  - [x] Fix released for all plugins (mostly done, not treating this as a blocker)
- [x] Merge this PR
- [ ] Release `pytest-xdist` 2.0 :tada:

### CODE REVIEW

**Comment by Zac-HD** [comment]
And it looks like we'll need to start with some upstream fixes, and then bump the minimum version of `pytest` that `pytest-xdist` works with.

For future reference, if we're deprecating an attribute we should really turn it into a property which emits deprecation warnings so that people know they need to migrate - in this case even the pytest team seems to have missed it!

**Comment by hugovk** [comment]
Some other pytest-dev repos that'll need updating:

https://github.com/search?l=Python&q=sort%3Aupdated-desc+slave+org%3Apytest-dev+xdist&type=Code

**Comment by nicoddemus** [comment]
I've posted an issue to all repositories from @hugovk's search warning about the upcoming changes. 👍

**Comment by asottile** [comment]
for those looking for messaging, the minimum version necessary appears to be pytest-xdist 1.22.3

**Comment by Zac-HD** [comment]
I've bumped the dependency to `pytest >= 6.0.0rc1`, and everything works :tada: 

@nicoddemus @RonnyPfannschmidt @asottile - the plan was to wait for 6.0.0 final, but I guess we could also do a `pytest-xdist` 2.0.0rc1 prerelease if users are installing preview versions at the moment?

**Comment by Zac-HD** [comment]
@nicoddemus (et al :heart:), pytest 6 is out :tada: and I think we're finally ready to merge this!

Then merge #557 into master, and do the release magic...

**Comment by hugovk** [comment]
All the issues/PRs referencing this one are now closed/merged 👍

**Comment by nicoddemus** [comment]
Hey everyone, sorry for the delay here; I did not forget this, it is on my radar, I will get to it sometime this week. 👍

**Comment by nicoddemus** [comment]
Merged! 🎉 

Thanks a lot @Zac-HD, for implementing it here and the amazing work on pursuing/helping other plugins to get compatible, @hugovk for neatly cleaning up old Python 2.7 support (as he is prone to do! 😁), and everybody else who participated/helped.

**Comment by nicoddemus** [comment]
I want to take a pass at the opening PRs before releasing 2.0, will try to do it by the end of the week. 👍

**Pull request merged**
