### PR TITLE
Add appveyor support

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Any guess as to why the failures in `py26` and `py34-pytest26`? :worried:

**Comment by RonnyPfannschmidt** [comment]
Yes, its a ordering issue in the internal statemachine

Please install setuptools-scm with tox

**Comment by nicoddemus** [comment]
Hmmm I see it is already mentioned in the `deps` section in the `tox.ini` file:

```ini
[testenv]
changedir=testing
deps =
    pycmd
    setuptools_scm # to avoid .eggs
    pytest24: pytest~=2.4.0
    pytest25: pytest~=2.5.0

    pytest26: pytest~=2.6.1
    pytest27: pytest~=2.7.2
    pexpect: pexpect
```

**Comment by RonnyPfannschmidt** [comment]
problem is that tox runs setup.py in the host env -so you need both tox and setuptools_scm

**Comment by nicoddemus** [comment]
> problem is that tox runs setup.py in the host env -so you need both tox and setuptools_scm

Got it, thanks! :smile:

Let's see how that fares.

**Comment by nicoddemus** [comment]
Hmmm same error. I will try to reproduce this at home, but meanwhile do you have any other tips?

**Comment by RonnyPfannschmidt** [comment]
thats a state ordering bug - its hard to trigger on normal fast computers, but seems quite noticable on the ci systems, the pr is good

**Pull request merged**
