### PR TITLE
Add a hook to allow overriding the remote module that's executed by e…

### PR DESCRIPTION
**Pull request by illiterati1**
…xecnet

Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [x] Make sure to include reasonable tests for your change if necessary

- [x] We use [towncrier](https://pypi.python.org/pypi/towncrier) for changelog management, so please add a *news* file into the `changelog` folder following these guidelines:
  * Name it `$issue_id.$type` for example `588.bugfix`;
  * If you don't have an issue_id change it to the PR id after creating it
  * Ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example:

    ```
    Fix issue with non-ascii contents in doctest text files.
    ```

### CODE REVIEW

**Comment by illiterati1** [comment]
It became useful for my organization to be able to override what module is actually run on the remote nodes. It's a fairly minimal change to the existing code but this allows further flexibility in concert with the scheduler hook.

**Comment by RonnyPfannschmidt** [comment]
given that i plan to make xdist independent of exec-net, this hook as proposed creates problems as it ties down a direct and massive dependency that permates the api

**Comment by illiterati1** [comment]
I'm happy to try to make the api more generic and future-proof, though I'm not familiar enough with distributed stuff to be able to do that off the top of my head. How would the invocation differ with multiprocess or mitogen?

**Comment by RonnyPfannschmidt** [comment]
got one it wouldnt be a module for any of those tools

**Comment by illiterati1** [comment]
I've come up with a preliminary solution. It's a pretty simple wrapper class that can either take a function or a module which seem to be the most common methods of remote execution. If in the future xdist is using something that does not accept modules we can wrap the module in a function before returning it. I would do that right now but I believe it would run afoul of execnet's limitation on pure functions.

**Comment by illiterati1** [comment]
The failing tests seem related to upstream pytest changes

**Comment by nicoddemus** [comment]
Thanks @illiterati1!

The implementation is a good start, but I'm not sure it will be suitable for a general solution in the future, given that this hook will not really be reusable with a multiprocessing backend (I think).

But perhaps we should consider that, in order to change the backend, we will need anyway to remove/deprecate some/most of the existing hooks (for example `pytest_xdist_newgateway(gateway)`), so perhaps the original shape of the PR was OK, it would introduce just another hook which will need to be deprecated/removed in the future (which might take a lot of time to materialize given our limited resources for the magnitude of such refactoring of the backend).

What do you think @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
thats thinkable

**Comment by nicoddemus** [comment]
Thanks @RonnyPfannschmidt 

I would say to get this PR back to how it was in 7fb7bd9d044cb9dd58e94ce42366768d5e401c75 then. 👍

**Comment by RonnyPfannschmidt** [comment]
yes

**Comment by illiterati1** [comment]
Easy enough

**Pull request merged**
