### PR TITLE
Tests: Unset PYTEST_XDIST_AUTO_NUM_WORKERS when the behavior without the envvar is asserted

### PR DESCRIPTION
**Pull request by hroncok**
- [x] Make sure to include reasonable tests for your change if necessary

- [x] We use [towncrier](https://pypi.python.org/pypi/towncrier) for changelog management, so please add a *news* file into the `changelog` folder following these guidelines:
  * Name it `$issue_id.$type` for example `588.bugfix`;
  * If you don't have an issue_id change it to the PR id after creating it
  * Ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example:

    ```
    Fix issue with non-ascii contents in doctest text files.
    ```

### CODE REVIEW

**Comment by hroncok** [comment]
Alternatively, this could be an autouse fixture in the file that does this. Let me know if you prefer that.

**Review by RonnyPfannschmidt — APPROVED** [review]
Lovely, thanks, 

as nitpick it might be nice to add `raising=` in front of the False

**Comment by hroncok** [comment]
> as nitpick it might be nice to add `raising=` in front of the False

Done.

**Review by nicoddemus — APPROVED** [review]
Thanks!

**Pull request merged**
