### PR TITLE
Acceptance tests: parametrize some tests with scheduler argument

### PR DESCRIPTION
**Pull request by amezin**
Parametrize some trivial test cases, and tests for previously fixed scheduler-related bugs.

### CODE REVIEW

**Review by RonnyPfannschmidt — COMMENTED** [review]
At first glance none of those tests add value for the schedulers

I'm not keen to add fake confidence

**Comment by amezin** [comment]
@RonnyPfannschmidt

`test_issue_594_random_parametrize` - mismatching collection detection is implemented by schedulers. And the code is even a bit different in `LoadScheduling` and `LoadScopeScheduling`.

`test_fixture_scope_caching_issue503` - yes, my mistake, `nextitem` isn't affected by schedulers directly.

Additionally, I think some basic things are worth checking for all schedulers - that they don't hang, the output is matching the expected (that no tests are lost, for example), at least on a few samples. How should I approach it?

**Comment by RonnyPfannschmidt** [comment]
A key issue here is that just adding schedulers to tests that don't affect them (like - n1 ones) is simply not exerting them

The schedulers should have a specific test set that includes crashing /hanging workers

**Comment by RonnyPfannschmidt** [comment]
Additionally we ought to have unit tests for that stuff (but atm we just don't

**Comment by amezin** [comment]
> A key issue here is that just adding schedulers to tests that don't affect them (like - n1 ones) is simply not exerting them

`-n1` is a corner case. Which may be overlooked when testing scheduler changes manually. But, of course, tests with multiple workers will be needed too.

> Additionally we ought to have unit tests for that stuff (but atm we just don't

There are scheduler unit tests in `test_dsession.py`. However, unit tests only verify that the scheduler meets test author's expectations (that it emits the expected sequence of commands). Not that everything works correctly together. I'd be much more confident if there were both unit tests and end-to-end tests.

**Comment by nicoddemus** [comment]
(Joining late in the discussion)

While I understand that the added tests are not adding full confidence over the different schedulers, I *do* see value in them as at least they exercise common use-cases which should work the same across all schedulers.

I don't see this as fake confidence (as in "we are now at 100% confidence everything is correctly exercised"), but only as moving the "confidence bar" a little bit towards 100%, which is useful.

Adding this bit of exercise for common cases does not exclude (or diminish) the need of adding proper unittests for the schedulers in the future, so I'm :+1: on reopening and merging this.

**Review by nicoddemus — APPROVED** [review]

**Comment by amezin** [comment]
@RonnyPfannschmidt convinced me that this particular attempt isn't good enough.

While I believe there should be end-to-end tests (written from requirements, not knowledge of internal implementation details) that somehow verify schedulers, this particular pull request doesn't add much value.

**Comment by nicoddemus** [comment]
OK then, I surrender. :grin:

**Pull request closed without merging**
