### PR TITLE
Add worker_id into TestReport

### PR DESCRIPTION
**Pull request by KKoukiou**
I think this change is enough for the purpose of this [issue](https://github.com/pytest-dev/pytest-xdist/issues/118)
Though, I am not really familiar with the project, so please let me know if I am missing something.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
good work 

based on 
https://github.com/pytest-dev/pytest-xdist/blob/dc646cebcc8e30d2cb80e477192aff63f1c26ac9/xdist/slavemanage.py#L305
and
https://github.com/pytest-dev/pytest-xdist/blob/dc646cebcc8e30d2cb80e477192aff63f1c26ac9/xdist/slavemanage.py#L325-L329

this change is good,
do you think you can add a test for it without too much effort ?

**Comment by nicoddemus** [comment]
Could you also add a new changelog entry and perhaps add a note to the `README` about this new feature?

**Comment by KKoukiou** [comment]
@RonnyPfannschmidt @nicoddemus thanks for the feedback. I 'll adjust the patch and resend with your comments!

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt could you at least add a `CHANGELOG` entry?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus there is one already

**Pull request merged**
