### PR TITLE
Noisy rsync

### PR DESCRIPTION
**Pull request by cmecklenborg**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [ ] Make sure to include reasonable tests for your change if necessary

- [x] We use [towncrier](https://pypi.python.org/pypi/towncrier) for changelog management, so please add a *news* file into the `changelog` folder following these guidelines:
  * Name it `$issue_id.$type` for example `588.bugfix`;
  * If you don't have an issue_id change it to the PR id after creating it
  * Ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example:

    ```
    Fix issue with non-ascii contents in doctest text files.
    ```

### CODE REVIEW

**Comment by nicoddemus** [comment]
Ignoring the py38-windows failures because they should be fixed in the next pytest release and are not related to pytest-xdist.

**Comment by nicoddemus** [comment]
Hey @cmecklenborg, thanks for the PR and we're terribly sorry for the silence here, this must have fell through the cracks.

**Comment by cmecklenborg** [comment]
@nicoddemus Thanks for the merge! Sorry for not following up on this sooner myself. :grimacing:

**Comment by nicoddemus** [comment]
Not at all, we dropped the ball here. But thanks again!

**Pull request merged**
