### PR TITLE
travis: use tox-travis

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
Please rebase and correct the rebase artifacts

**Comment by xoviat** [comment]
@RonnyPfannschmidt done.

**Comment by RonnyPfannschmidt** [comment]
thanks, any idea why the pytest 2.9 env fails?

**Comment by xoviat** [comment]
I have no idea.

**Comment by nicoddemus** [comment]
Thanks for the contribution, but what are the benefits to switch over to `tox-travis` for `pytest-xdist`? I like `tox-travis` for projects with simple tox files (basically only `py27`, `py35`, etc test envs), which is not the case here. Using tox-travis here means that we cram more test runs into less jobs, which will probably increase the overall build time. Additionally, it creates an inconsistency to what we have for AppVeyor: having both travis and appveyor list the test envs in the same way is good consistency IMO. 

I'm just curious in case there are obvious benefits that I'm missing. 😁

**Comment by nicoddemus** [comment]
> Running python versions other than the version specified is not officially supported on travis-ci.

I didn't know that, thanks. I thought the currently installed Python versions were part of the VM image except for py35 and py36, because they are not in the base image and are installed separately when one asks for that Python version in `.travis.yml`. But I thought that was temporary and Travis would eventually add py35 and py36 to the base image.

Reading over the `.travis.yml` again I can see that it is in fact much cleaner, so I guess that outweighs the loss of consistency with `appveyor.yml`.

I triggered the build again to see if the failure was a temporary error.

**Comment by nicoddemus** [comment]
Yep it was. :grin: 👍

**Comment by RonnyPfannschmidt** [comment]
can we get another pr to ensure matrix expansion?
else i#ll try to take a look at the weekend

**Comment by nicoddemus** [comment]
>  What has actually happened is that there are no tests run for py36 because people are waiting for travis to 'update their images', which is not going to happen.

I concur with that, I'm guilty of this myself in a few minor projects. 😉

**Pull request merged**
