### PR TITLE
Make "--pdb" imply "--dist no"

### LINKED ISSUE #549: Make "--pdb" imply "--dist no"
If I have this in my `pytest.ini`:

```
[pytest]
addopts = --numprocesses auto
          --dist loadscope
```

... I get told off that I have a problem with my `-n` option when trying to use `--pdb`:

```
$ pytest --pdb
ERROR: --pdb is incompatible with distributing tests; try using -n0 or -nauto.
```

Currently using `--pdb` with `-nauto` implies `-n0`, I think it should also imply `--dist no` for consistency?

### PR DESCRIPTION
**Pull request by adamchainz**
Fixes #549.

Here's a quick checklist that should be present in PRs:

- [x] Make sure to include reasonable tests for your change if necessary

- [x] We use [towncrier](https://pypi.python.org/pypi/towncrier) for changelog management, so please add a *news* file into the `changelog` folder following these guidelines:
  * Name it `$issue_id.$type` for example `588.bugfix`;
  * If you don't have an issue_id change it to the PR id after creating it
  * Ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example:

    ```
    Fix issue with non-ascii contents in doctest text files.
    ```

### CODE REVIEW

**Comment by blueyed** [comment]
Maybe relevant: https://github.com/pytest-dev/pytest-xdist/pull/502

**Comment by adamchainz** [comment]
Yes, will happily rebase if that gets merged.

**Comment by adamchainz** [comment]
Tests are now passing since `master` got fixed.

**Comment by adamchainz** [comment]
Thanks for the update

**Comment by nicoddemus** [comment]
Thanks a lot @adamchainz! 🙇

**Pull request merged**
