### PR TITLE
Release 1.28.0

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@blueyed gentle ping. 😁

**Comment by blueyed** [comment]
Friendly pong.
You can pick one of these in return: https://github.com/pytest-dev/pytest/pulls/blueyed

(not sure what's up with Travis here?)

**Comment by nicoddemus** [comment]
> You can pick one of these in return: pytest-dev/pytest/pulls/blueyed

Sure, will do!

> (not sure what's up with Travis here?)

Strange, https://www.traviscistatus.com/ shows that there's no back log for Linux jobs...

**Comment by blueyed** [comment]
Restart it maybe?

**Comment by nicoddemus** [comment]
It's now going. 👍

**Pull request merged**
