### PR TITLE
Mark test as complete at teardown.

### PR DESCRIPTION
**Pull request by reginaldl**
Possible fix for #124.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
please add an accompanying test

**Comment by reginaldl** [comment]
Hi Ronny!

I added a test and improved another one ;)
Let me know if this fix needs additional work.

**Comment by nicoddemus** [comment]
Thanks a lot for this!

LGTM  as well. Would you mind adding a CHANGELOG entry?

**Comment by reginaldl** [comment]
Done! Any idea when 1.16 is going out?

**Comment by nicoddemus** [comment]
We can make a release as soon as this is merged I guess.

@RonnyPfannschmidt could you take a look and merge this if you are OK with it?

**Comment by RonnyPfannschmidt** [comment]
sorry for the long wait, it seems i had a situation where a bulk of notifications was marked read

**Pull request merged**
