### PR TITLE
Keep GitHub Actions up to date with GitHub's Dependabot

### PR DESCRIPTION
**Pull request by cclauss**
Creates automatic pull requests to upgrade GitHub Actions which will resolve the warnings like at the bottom right of https://github.com/pytest-dev/pytest-xdist/actions/runs/7703720389
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [x] Make sure to include reasonable tests for your change if necessary

- [x] We use [towncrier](https://pypi.python.org/pypi/towncrier) for changelog management, so please add a *news* file into the `changelog` folder following these guidelines:
  * Name it `$issue_id.$type` for example `588.bugfix`;
  * If you don't have an issue_id change it to the PR id after creating it
  * Ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example:

    ```
    Fix issue with non-ascii contents in doctest text files.
    ```

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]
Thanks! Let's see how this will play out. 👍

**Comment by nicoddemus** [comment]
I will wait a bit in case @RonnyPfannschmidt wants to chime in.

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by nicoddemus** [comment]
Thanks @cclauss!

**Comment by cclauss** [comment]
Generated
* #1016

**Pull request merged**
