### PR TITLE
broadcast child shouldstop or fail Fixes pytest-dev/pytest#5655

### PR DESCRIPTION
**Pull request by graingert**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [ ] Make sure to include reasonable tests for your change if necessary

- [ ] We use [towncrier](https://pypi.python.org/pypi/towncrier) for changelog management, so please add a *news* file into the `changelog` folder following these guidelines:
  * Name it `$issue_id.$type` for example `588.bugfix`;
  * If you don't have an issue_id change it to the PR id after creating it
  * Ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example:

    ```
    Fix issue with non-ascii contents in doctest text files.
    ```

### CODE REVIEW

**Comment by graingert** [comment]
@nicoddemus I tested this locally with my testcase here: https://github.com/pytest-dev/pytest/issues/5655

**Comment by graingert** [comment]
@nicoddemus I'm not sure what sort of test I should add here though

**Comment by graingert** [comment]
it also works for me on the big project I'm testing it on - not sure how to handle multiple simultaneous test failures though

**Comment by nicoddemus** [comment]
Hi @graingert,

Sorry for the delay!

I think an integration test with stepwise, like described in in #458 (I've moved it from `pytest` to this repository) should be enough.

Also please add a `458.bugfix.rst` CHANGELOG entry, something like:

```
The ``--stepwise`` option is now supported correctly.
```

**Comment by graingert** [comment]
It's not actually correct though, because when multiple tests fail the suite starts from a random test

**Comment by nicoddemus** [comment]
> It's not actually correct though

You mean the changelog message or the actual behavior being observed?

**Comment by graingert** [comment]
The new behaviour with this PR. It makes stepwise mostly workable but a bit
frustrating

**Comment by nicoddemus** [comment]
Definitely, but I'm not sure if we can improve that.

**Comment by graingert** [comment]
`-x` works perfectly however as it operates directly on the master process.
Is there a way for plugins to hook into DSession?

**Comment by nicoddemus** [comment]
> Is there a way for plugins to hook into DSession?

Not right now, but we can include that depending on what's needed.

**Comment by graingert** [comment]
@nicoddemus having worked with this for a while, it's actually extremely frustrating! Quite often failing tests are skipped over, or not run and skipped over the next session

**Comment by nicoddemus** [comment]
> @nicoddemus having worked with this for a while, it's actually extremely frustrating! Quite often failing tests are skipped over, or not run and skipped over the next session

Sorry to hear. Does this PR makes things better for you?

**Comment by graingert** [comment]
Sorry I meant that this pr takes stepwise+xdist from not working at all to a frustrating half-working atate

**Comment by nicoddemus** [comment]
Ahh OK, thanks for the clarification. 👍

**Comment by graingert** [comment]
Is there a way to make xdist wait for all currently executing tests before
stopping at shouldstop

**Comment by nicoddemus** [comment]
Closing this as stale, but feel free to reopen if you want to tackle this again @graingert!

**Pull request closed without merging**
