### PR TITLE
[WIP] Simplify AppVeyor build and add badge

### PR DESCRIPTION
**Pull request by nicoddemus**
There's no point in creating a huge matrix because AppVeyor does
not run the builds in parallel; in fact it will greatly increase
build times as each matrix will boot a separate VM to execute on.

Also removed install.ps1 and run_with_env.cmd, which are only
really required if you have C extensions.

**Please do not merge**, this is rebased on #24 and I would like to clean up this branch after #24 is merged.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
:+1:

**Comment by nicoddemus** [comment]
I was planning on rebasing it first... but oh well. :grin:

**Comment by RonnyPfannschmidt** [comment]
sorry, this was just looking good and i was trigger happy ^^

**Comment by nicoddemus** [comment]
No worries :smile:

**Pull request merged**
