### PR TITLE
Increase pexpect timeouts to prevent tests from failing

### PR DESCRIPTION
**Pull request by mgorny**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [ ] Make sure to include reasonable tests for your change if necessary

- [ ] We use [towncrier](https://pypi.python.org/pypi/towncrier) for changelog management, so please add a *news* file into the `changelog` folder following these guidelines:
  * Name it `$issue_id.$type` for example `588.bugfix`;
  * If you don't have an issue_id change it to the PR id after creating it
  * Ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example:

    ```
    Fix issue with non-ascii contents in doctest text files.
    ```

### CODE REVIEW

**Comment by mgorny** [comment]
Do you consider this change worth a changelog entry?

**Comment by nicoddemus** [comment]
Hi @mgorny, thanks for the PR!

Linting failed, I've fixed it and pushed to your branch.

> Do you consider this change worth a changelog entry?

Not necessary, this is an internal change and not visible to users. 👍 

Can you describe why this change is necessary though? I've never seen those tests fail.

**Comment by mgorny** [comment]
To be honest, I've tried three times and got all three tests failing every time (once with PyPy3, twice with CPython 3.8). It might be that my system is slow, background tasks keep it slow-ish or just Portage/sandbox causes unexpected slowness. In any case, increasing the timeout fixed it for me.

I can imagine our arch teams would hit it when testing pytest-xdist on more exotic architectures like ARM.

**Comment by nicoddemus** [comment]
OK, thanks for the explanation.  

I don't see any harm in increasing the timeout, was just curious and wanted to leave it registered here the reasons. 👍

**Pull request merged**
