### PR TITLE
Fix year in project documentation

### PR DESCRIPTION
**Pull request by n8creator**
Fixed an outdated year in the project documentation

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
This needs to be the start year or a range, current year is always wrong

**Review by RonnyPfannschmidt — CHANGES_REQUESTED** [review]
I missed when this was made wrong the first time, we need start year or a range

**Comment by nicoddemus** [comment]
I suggest just a start date, we can use the one for the first tag:

image

We do that in pytest: https://github.com/pytest-dev/pytest/blob/271bdf6c235360131ae5a3e3426f39174811c0cf/LICENSE#LL3C15-L3C20

**Comment by cclauss** [comment]
See the highest-ranked answer...
https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by nicoddemus** [comment]
Updated it to use the copyright for the first commit. 👍

**Comment by nicoddemus** [comment]
Thanks @n8creator!

**Review by cclauss — APPROVED** [review]

**Pull request merged**
