### PR TITLE
[WIP] Issue #130 

### PR DESCRIPTION
**Pull request by timyhou**
Updated serialize_report and unserialize_report to allow passing of additional exception info using ReprExceptionInfo. We could also use `ExceptionChainRepr` instead actually. I mostly just took a suggestion from mszpala and ran with it. 

This addresses issue #130.

Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [x] Make sure to include reasonable tests for your change if necessary

- [x] Add a new news fragment into the changelog folder, following these guidelines:
  * Name it `$issue_id.$type` for example `588.bug`
  * If you don't have an issue_id change it to the PR id after creating it
  * Ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example:

    ```
    Fix issue with non-ascii contents in doctest text files.
    ```

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
the approach looks interesting, unfortunately it broke the build at least on old pytest

@nicoddemus this one is in particular an issue since we started to use tox-travis - by now im relatively certain that i want to get rid of tox-travis, it breaks results in some cases

**Comment by timyhou** [comment]
I am taking a look at the failures. I admit I didn't test it out on older versions of python so I'll give it another go.

**Comment by RonnyPfannschmidt** [comment]
@timyhou i stongly suggest using tox locally - we may be fine with dropping pytest 2.x support over this

@nicoddemus oppinions?

**Comment by nicoddemus** [comment]
> we may be fine with dropping pytest 2.x support over this

I agree, we might require pytest >= 3 then

**Comment by timyhou** [comment]
Should I add a commit with an updated tox.ini to not bother testing pytest 2.x to let the Travis CI and appveyor checks try again?

**Comment by nicoddemus** [comment]
Yes please. 😁

**Comment by timyhou** [comment]
Sorry the commit history is going to get kind of messy as I realized I forgot to upset the appveyor.yml and setup.py. If this becomes a thing, I promise to squash it properly.

**Comment by timyhou** [comment]
The test I am having trouble with right now is [TestFunctional.test_xfail_passes](https://github.com/pytest-dev/pytest-xdist/blob/master/testing/test_looponfail.py#L271). I can reproduce the failure locally through tox and by setting up an virtualenv that the spawn.out file doesn't seem to have `LOOPONFAILING`  in the log.  I can see though it does mark the test as "xpass" however I am hesitant to have the test not verify the LOOPONFAILING part since I am unfamiliar with it. 

The other test failures on Travis I haven't been able to reproduce locally though and the "fixed" themselves the last run on TravisCI? They seemed to only be coming from the pexpect configurations. 

Those tests were:
- [ ] [test_keyboard_interrupt_dist](https://github.com/pytest-dev/pytest-xdist/blob/master/testing/acceptance_test.py#L248-L258) (only on py27). Similar issue where the spawn.out is missing text. 
- [ ] [test_looponfail_removed_test](https://github.com/pytest-dev/pytest-xdist/blob/master/testing/test_looponfail.py#L196-L215)

**Comment by timyhou** [comment]
I made a branch with a a cleaner git history on my fork. Would it be better to close this PR and start a new one against the better branch?

**Comment by nicoddemus** [comment]
@timyhou you can push-force to this branch, the PR will update automatically.

**Comment by nicoddemus** [comment]
Or feel free to create to create a new PR, no problem with that. 👍

**Comment by timyhou** [comment]
Updated.

**Comment by nicoddemus** [comment]
Awesome, thanks! I checked locally and it works! 👍

**Comment by nicoddemus** [comment]
Hmm I might have pushed that merge button too soon, I could have sworn @RonnyPfannschmidt was ok with the change already. @RonnyPfannschmidt what do you think?

**Comment by RonnyPfannschmidt** [comment]
We should move this to pytest core eventually

**Comment by messa** [comment]
Hi, are you sure about this? :)

```python
if 'reprcrash' and 'reprtraceback' in reportdict['longrepr']:
```

Maybe if I add some parenthesis how it is evaluated by Python:

```python
if ('reprcrash') and ('reprtraceback' in reportdict['longrepr']):
```

**Comment by nicoddemus** [comment]
@messa oh good catch, this definitely should be:

```python
if 'reprcrash' in reportdict['longrepr'] and 'reprtraceback' in reportdict['longrepr']:
```

Would you like to open a PR with this fix?

**Comment by messa** [comment]
@nicoddemus  Done: #213

**Pull request merged**
