### PR TITLE
Sort collected tests

### PR DESCRIPTION
**Pull request by kirbyfan64**
Fixes pytest-dev/pytest#596 (and maybe also pytest-dev/pytest#920, but I can't reproduce it).

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
At first glance This breaks fixture scope based ordering

**Comment by nicoddemus** [comment]
> At first glance This breaks fixture scope based ordering

Does pytest does any reordering currently based on session-scoped fixtures?

Other than that, I'm not sure this is the way to go because it will completely change the expected order of test execution... not that it is guaranteed when using `pytest-xdist` anyway. Any other thoughts?

**Comment by RonnyPfannschmidt** [comment]
i have a proposal for general test ordering, will explain at the sprint

**Comment by RonnyPfannschmidt** [comment]
closing for now, this solution alters fixture setup/teardown expectations and one of the goals is to teach xdist about the scopes and caches to better utilize each nodes scoped caches

**Pull request closed without merging**
